### ISSUE TITLE
Cloning Muxy Extension Rig

### ISSUE THREAD

**Issue by Brayden** [muxy/extensions-rig#1]
Running the commands in the README.md it states to:

```
git clone https://github.com/muxy/muxy-extension-rig
```

However, when attempting to execute this command you get the following response:

```
Cloning into 'muxy-extension-rig'...
remote: Repository not found.
fatal: repository 'https://github.com/muxy/muxy-extension-rig/' not found
```

**Comment by peter-bonanni** [comment]
Thanks for pointing out this typo in the docs. You're still able to clone using:

`git clone https://github.com/muxy/extension-rig`

Correct?

We'll be getting out a patch ASAP to fix the documentation. 

edit: typoed the url myself sorry for the confusion @Brayden

**Comment by Brayden** [comment]
Unfortunately I am still unable to clone from that location:

```
git clone https://github.com/muxy/muxy-extension-rig
Cloning into 'muxy-extension-rig'...
remote: Repository not found.
fatal: repository 'https://github.com/muxy/muxy-extension-rig/' not found
```

**Comment by camr** [comment]
Updated the documentation. The correct clone command is:

`git clone https://github.com/muxy/extensions-rig`

**Comment by Brayden** [comment]
👍 I had used that clone command originally after the documentation one failed, just wanted to make sure that was the correct one. Thanks!
