### ISSUE TITLE
`Uncaught TypeError: Util.environmentDetector is not a function`

### ISSUE THREAD

**Issue by bcjordan** [muxy/extensions-rig#3]
Hey gang, awesome looking rig! Considering using this to build a Twitch extension for Clone Drone in the Danger Zone.

I'm getting the following error when testing out `hello_world` example:

`Uncaught TypeError: Util.environmentDetector is not a function`

Possibly some sort of version mis-match?

**Comment by DDRBoxman** [comment]
Looks we might have introduced that bug during some refactoring in https://github.com/muxy/extensions-js

I'll take a look at it.

**Comment by bcjordan** [comment]
Awesome, thanks! & found a workaround of building my own version with that server-side section commented out.

**Comment by bcjordan** [comment]
Curious (& happy to discuss on discord or move to a different doc-related issue) -- what's the process like for going from extensions-rig local development to publishing the work in progress as a Twitch Extension?

Is it roughly:

1. Ensure .js assets are located within the project folder
1. Zip up what's in `src/hello_world`
2. Upload that to Twitch directly

Is there any migration required to make pubsub work there? E.g. making it use Twitch's built-in pubsub?

**Comment by DDRBoxman** [comment]
Yeah, submission is really straightforward.

If you're using the Muxy SDK we automatically switch over to the Twitch based pubsub when it's running on Twitch. There are actually a few things that switchover based on the environment, running outside of twitch we generate "fake" auth credentials that allow you to use the SDK, and then when that's running on Twitch it will use the JWT that they send down for each user.

**Comment by DDRBoxman** [comment]
I went ahead and added an extension channel to our discord if you have any more questions: https://discord.gg/0upJkmAJGFe2yK09

**Comment by bcjordan** [comment]
That's awesome! Sounds super streamlined 👍 Will definitely be looking at this as an implementation option.

**Comment by camr** [comment]
Pushed a new version of the library (1.0.5) yesterday to GitHub and the CDN with fixes for this issue.
